spring:
  datasource:
   # url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:E:/descargas mega/bootcamp/bootcamp/src/main/resources/data.sql
    
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  profiles:
      active: 
      - admin
      - prod



management:
   endpoints:
      web:
         exposure:
            include: "*"
            
server:
   port: 8090  
   

       
course:
   message: "Hello World normal!"
   